### ISSUE TITLE
TMOP not charging the Word Embeddings

### ISSUE THREAD

**Issue by dahrs** [hlt-mt/TMOP#3]
Hello,
I'm a researcher at the University of Montreal and we are currently working on a project that would implement TMOP but we are having a bit of a problem making the Word embedding filters activate. Instead of vectors for all words, we are getting empty lists. After analyzing the code, it MIGHT be because of the variable "model_file_name", which contains a path to a folder "models/vectors_" and that does not exist in the environment. There is a folder named models but contains no folders or files named vector_.
We know it's been a while but we would appreciate if you could pinpoint us to how your folder environment was structured and how solve this problem.
Thanking you in advance,
David

**Comment by bhardwaj1230** [comment]
This is no more supported and doesn't work !!!
Don't waste your time @dahrs  with this tool.

**Comment by katerpillar** [comment]
Dear David,

I'm really sorry for the delay.
Can you tell me more about your config file?
Do you have the "source language" and "target language" in your options?
For example, if you have "eng" and "deu" as the source and target
languages, the model will create a file in the "models" folder with the
name "vectors_engdeu".

I'm also trying to update the code, so you can use other word embeddings if
needed.

We are sorry again for the delay in response.
Regards,
Masoud

**Comment by dahrs** [comment]
Hi Massoud,
After a while I finally solved the problem I was having. It was simply a problem with the version of Python I was using.
You can close the issue.
Thanks for the response though.
David
